version: "3.9"

volumes:
  pgdata: {}

services: 
  web: 
    container_name: flask_web
    build:
     context: app
     target: builder
    ports: 
      - '8000:8000'
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - app/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
